pipeline {
	agent any
	
    stages {

		stage('Clone repo') {
			steps {
				sh 'echo "downloading repo..."'
				sh "git clone https://github.com/mcherkashyn/pet-projects.git"
				sh "ls"
				sh "pwd"
			}
		}

		stage('TF Init&Plan') {
			steps {
				sh 'cd pet-projects/docker_with_aws/'
				sh 'terraform init'
				sh 'terraform plan'
			}      
		}

		stage('Approval') {
			steps {
				script {
					def userInput = input(id: 'confirm', message: 'Apply Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ])
				}
			}
		}

		stage('TF Apply') {
			steps {
				sh 'cd pet-projects/docker_with_aws/'
				sh 'terraform apply -input=false'
			}
		}
		stage('Remove the old files'){
			steps {
				sh 'echo "deleting the files..."'
				sh "rm -r pet-projects"
			}
		}
	} 

}
