pipeline {
	agent any
	
    stages {


		stage('fetch_latest_code') {
			steps {
			git credentialsId: 'git_pass', url: 'https://github.com/mcherkashyn/pet-projects.git'
			}
		}

		stage('TF Init&Plan') {
			steps {
				sh 'cd pet-projects/docker_with_aws/'
				sh 'terraform init'
				sh 'terraform plan'
			}      
		}

		stage('Approval') {
			steps {
				script {
					def userInput = input(id: 'confirm', message: 'Apply Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ])
				}
			}
		}

		stage('TF Apply') {
			steps {
				sh 'cd pet-projects/docker_with_aws/'
				sh 'terraform apply -input=false'
			}
		}
		
	} 

}
