pipeline {
	agent any
	
    stages {


		/*
		stage('fetch_latest_code') {
			steps {
				git credentialsId: 'git_pass', url: 'https://github.com/mcherkashyn/pet-projects'
			}
		}
		*/

		stage('TF Init&Plan') {
			steps {
					sh "cd docker_with_aws/"
					sh "ls"
					sh "pwd"
					sh 'terraform init'
					sh 'terraform plan'
				}
			}      

		stage('Approval') {
			steps {
				script {
					def userInput = input(
						id: 'confirm', 
						message: 'Apply Terraform?', 
						submitterParameter: 'approved_by',
						parameters: [
							[$class: 'BooleanParameterDefinition', 
							defaultValue: false, 
							description: 'Apply terraform', 
							name: 'confirm']
						]
					)
					if (!userInput.confirm) {
						error('Deployment was not approved')
					}
				}
			}
		}

		stage('TF Apply') {
			steps {
					sh "cd docker_with_aws/"
					sh 'terraform apply -input=false'
				}
			}
		}	
} 

