name: Deploy Flask app to AWS with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        
      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r ci_cd_with_aws/flaskapp/requirements.txt
        
      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
          
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.3.9

      - name: Terraform init, plan and apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "** Running Terraform Init**"
          terraform init -input=false
      
          echo "** Running Terraform Plan**"
          terraform plan
          
          echo "** Running Terraform Apply**"
          terraform apply -auto-approve -input=false
        working-directory: "./ci_cd_with_aws"
