name: Deploy Flask app to AWS with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.9

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r ci_cd_with_aws/flaskapp/requirements.txt

      - name: Build and deploy app
        run: |
          source env/bin/activate
          cd ci_cd_with_aws/
          terraform init
          terraform plan
          terraform apply -auto-approve

      - name: Terraform output
        run: |
          terraform output -json > terraform_output.json
          cat terraform_output.json | jq


