name: Build, Test and Deploy a web-app

on:
  push:
    branches: [ "main" ]
  
permissions:
  contents: read

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get install python3
        sudo apt install python3-pip -y
        pip3 install Flask
        pip3 install pytest
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python --version
        ls
        pytest ./ci_cd_with_aws/flaskapp/flaskapp.py
   
