name: Build and Deploy a web-app

on:
  push:
    branches: [ "main" ]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Deploy to AWS
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: hashicorp/terraform-github-actions@master
      with:
        args: |
          init
          plan
          apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
   
