name: Deploy Flask app to AWS with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.9

      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r ci_cd_with_aws/flaskapp/requirements.txt

      - name: Terraform bild and delpoy app
        env:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          source env/bin/activate
          cd ci_cd_with_aws/
          terraform init
          terraform plan
          terraform apply -auto-approve
          
      - name: Terraform output
        run: |
          terraform output -json > terraform_output.json
          cat terraform_output.json | jq


